blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Blogs API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('decode_blogs.urls')),
    path('authe/', include('decode_authe.urls')),
    url('swagger/', schema_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/decode_authe/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from . import views


app_name = 'decode_authe'

urlpatterns = [
    path('signup/',views.SignUpUser.as_view(), name='signup'),
    path('signin/',views.SignInUser.as_view() ,name='signin'),
    path('signout/',views.signout_user , name='signout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),


    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/user/', views.UserViewSet.as_view({'get': 'retrieve', 'post': 'create'})),

]

blog/decode_blogs/urls.py
from django.urls import path, include
from . import views

app_name = 'decode_blogs'

urlpatterns = [
    path('', views.Home, name="home"),
    path('blogs/<int:category_id>/', views.site_category, name='category'),
    path('add/', views.AddBlog.as_view(), name='add'),
    path('search/', views.BlogSearchView.as_view(), name='blog-search'), # ! #
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete'), 
    path('edit_blog/<int:blog_id>/', views.EditBlog.as_view(), name='edit'),


    path('cmadd/', views.AddComment.as_view(), name='cmadd'),
    path('testcommentview/<int:blog_id>/', views.BlogDetail.as_view(), name='comments-category'),
    path('delete_comment/<int:blog_id>/', views.delete_comment, name='delete-comment'), 

    
    path('', include('rest_framework.urls')),
    path('', views.BlogListAPIView.as_view()),
    path('<int:pk>/',views.BlogDetailAPIView.as_view()),
]

blog/decode_blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import datetime
import uuid

# Create your models here.

def uniq_name_upload(instance, filename):
    new_file_name = f"{uuid.uuid4()}.{filename.split('.')[-1]}"
    return f'images/{new_file_name}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name
    
class Blog(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    image = models.ImageField(blank=True, upload_to=uniq_name_upload)
    description = models.TextField()
    date = models.DateTimeField(default=datetime.datetime.today())
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)     # !  1 #
    
    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    def __str__(self) -> str:
        return self.name
    
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000)
    date = models.DateTimeField(default=datetime.datetime.today())
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, default=1)

blog/decode_blogs/forms.py
from django import forms
from .models import *

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name', 'category', 'image', 'description', 'date']
        widgets = {
            'image': forms.FileInput(attrs={'class': 'fieldset button button-yellow input-file form-control'}),
            'description':forms.Textarea(attrs={'rows':5})
        }
        
    def save(self, commit):
        author = settings.AUTH_USER_MODEL.objects.get(id=self.data['author_id'])
        self.instance.author = author
        return super().save(commit)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'blog','text', 'date']
        widgets = {
            'description':forms.Textarea(attrs={'rows':3})
        }

class BlogSearchForm(forms.Form):
    search = forms.CharField(label='Поиск по блогам', max_length=100)    

blog/decode_blogs/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView     
from rest_framework.viewsets import ModelViewSet  
from rest_framework.decorators import action 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy 
from django.http import HttpResponse
from rest_framework.views import APIView     
from rest_framework.response import Response 
from django.views.generic import View
from .permissions import *
from .models import *
from .forms import *
from .serializer import *
from django.http import Http404


menu = [
    {'title':'Home', 'url':'decode_blogs:home'},
    {'title':'Description', 'url':'decode_blogs:category'},   # Определение заголовков страницы #
    {'title':'Регистрация', 'url':'decode_authe:signup'},
    {'title':'Вход', 'url':'decode_authe:signin'},
]

def Home(request):
    data = {
        'title':'Главная',
        'menu': menu,
        'categories': Category.objects.all(),
        'blogs': Blog.objects.all(),
    }

    return render(request, 'decode_blogs/Home.html',  data)


class CategoriesBlog(ListView):
    model = Blog
    template_name = 'decode_blogs/Home.html'
    context_object_name = 'categories'
    

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        
        # Передача контекстных данных  #
        context['title'] = 'Категории'
        context['menu'] = menu
        context['categories'] = Category.objects.all()

        return context
    
def site_category(request, category_id):
    blogs = Blog.objects.filter(category_id=category_id)
    categories = Category.objects.all()

    data = {
        'blogs':blogs,
        'categories':categories,
        'menu':menu,
        'title':'Статьи',
        'category_id':category_id
    }

    return render(request, 'decode_blogs/Home.html', context=data) 


class AddBlog(CreateView):
    form_class = BlogForm
    template_name = 'decode_blogs/Add-blogs.html'
    success_url = reverse_lazy('decode_blogs:home.html')     # Переход после создания блога #

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)

        context['title'] = 'Новый блог'
        context['menu'] = menu

        return context

def delete_blog(request, blog_id):           
    try:
        blog = Blog.objects.get(pk=blog_id)
        blog.delete()
        return redirect('decode_authe:profile')    # Переход после удаления #
    except Blog.DoesNotExist:
        return HttpResponse("Blog DoesNotExist") 

class EditBlog(UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'decode_blogs/Edit-blog.html'  
    success_url = reverse_lazy('decode_blogs:home')
    
    def get_object(self):
        blog_id = self.kwargs['blog_id']
        return Blog.objects.get(pk=blog_id)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
def profile(request):
    user = request.user
    user_blogs = Blog.objects.filter(author=user)

    return render(request, 'profile.html', {'user_blogs': user_blogs})


class BlogSearchView(View):
    template_name = 'decode_blogs/Home.html'

    def post(self, request):
        form = BlogSearchForm(request.POST)
        if form.is_valid():
            search_query = form.cleaned_data['search']    # Получение данных введенных в форму #
            blogs = Blog.objects.filter(name__icontains=search_query)  # Поиск записей в Blog  #
            return render(request, 'decode_blogs/Home.html', {'blogs':blogs, 'query':search_query})
        return render(request, self.template_name, {'form':form})

class AddComment(LoginRequiredMixin, CreateView):
    form_class = CommentForm
    template_name = 'decode_blogs/Add-comment.html'
    success_url = reverse_lazy('decode_blogs:home')     # Переход после создания продукта #
    
    def form_valid(self, form):
        form.instance.user = self.request.user  # Привязать комментарий к текущему пользователю #
        blog_id = self.kwargs.get('blog_id')

        if blog_id:                                # Связка комментария с определенным блогом #
            form.instance.blog_id = blog_id
        return super().form_valid(form)

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новый комментарий'
        context['menu'] = menu

        return context
    
def delete_comment(request, blog_id):           
    try:
        comment = Comment.objects.get(pk=blog_id)
        comment.delete()
        return redirect('decode_blogs:home')   
    except Comment.DoesNotExist:
        return HttpResponse("Comment DoesNotExist") 


class ShowComment(DetailView):
    model = Comment                     # Изменено на модель Comment, чтобы отображать комментарии
    template_name = 'decode_blogs/comment.html'
    pk_url_kwarg = 'comment_id'

    
    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_authenticated:
            return queryset.none()
        return queryset.filter(blog_id=self.blog_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обзор комментариев'
        context['blog'] = Blog.objects.get(id=self.blog_id)
        context['menu'] = menu
        return context
    

class BlogDetail(DetailView):
    model = Blog
    template_name = 'decode_blogs/comment.html'
    pk_url_kwarg = 'blog_id'
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обзор блога'
        context['comments'] = Comment.objects.filter(blog_id=self.kwargs['blog_id'])  # Комментарии относящиеся к этому блогу #
        context['categories'] = Category.objects.all()
        context['menu'] = menu
        return context


                # API #


class BlogListAPIView(ListCreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = (IsAdminOrReadOnly,)    # Класс для предоставления  доступа #


class BlogDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = (IsOwnerOrReadOnly,) 



class CommentListAPIView(ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (IsAdminOrReadOnly,)

class CommentDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (IsAdminOrReadOnly,) 

blog/decode_blogs/templates/decode_blogs/Add-blogs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Blog</title>
    <link rel="stylesheet" href="{% static 'decode_blogs/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/Edit-blog.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        <div class="header-div-2">
            <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
            <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>
            {% if user.image %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}

        </div>

    </header>
    <hr id="hr-line">

    <section class="main">
        <form action="{% url 'decode_blogs:add' %}" method="POST" enctype="multipart/form-data" class="form"> 
            {% csrf_token %}   <!--Специалынй токен -->
            {{ form.as_p }}
            <button type="submit" class="button">Сохранить</button>
    </section>

</body>
</html>

blog/decode_blogs/templates/decode_blogs/Add-comment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add comment</title>
    <link rel="stylesheet" href="{% static 'decode_blogs/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/add-comment.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        <div class="header-div-2">
            <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>  
            {% if user.image %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}
        </div>
    </header>
    <hr>


    <section class="main">
        <form action="{% url 'decode_blogs:cmadd' %}" method="POST" enctype="multipart/form-data" class="form"> 
            {% csrf_token %}   <!--Специалынй токен -->
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
    </section>
</body>
</html>

blog/decode_blogs/templates/decode_blogs/Delete-blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete blog</title>
</head>
<body>
    <form action="{% url 'delete_blog' blog.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить блог">
    </form>
</body>
</html>

blog/decode_blogs/templates/decode_blogs/Edit-blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit blog</title>
    <link rel="stylesheet" href="{% static 'decode_blogs/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/Edit-blog.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

                    
        <div class="header-div-2">
            {% if request.user.is_authenticated %}
                <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a> 
                {% if user.image %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
                {% else %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
                {% endif %}
            {% else %}
            <a href="{% url 'decode_authe:signin' %}" class="button-reg">SignIn</a>
            <a href="{% url 'decode_authe:signup' %}" class="button-reg">SignUp</a>
            {% endif %}
        </div>

    </header>
    <hr id="hr-line">
    {% if request.user.is_authenticated %}
    <section class="main">
        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="author_id" value="{{ user.id }}">
            <button class="button" type="submit">Сохранить</button>
    </section>
    {% endif %}

</body>
</html>

blog/decode_blogs/templates/decode_blogs/Home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'decode_blogs/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/home.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        
        <div class="header-div-2">
            {% if request.user.is_authenticated %}
            <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>  
                {% if user.image %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
                {% else %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
                {% endif %}
            {% else %}
            <a href="{% url 'decode_authe:signin' %}" class="button-reg">SignIn</a>
            <a href="{% url 'decode_authe:signup' %}" class="button-reg">SignUp</a>
            {% endif %}
        </div>

    </header>
    <hr id="hr-line">

    
    <section class="main">
        <div class="blogs">
            <h2 id="h2-blog">Блоги по программированию </h2>
            <p id="h2-p">Популярные и лучшие публикации по программированию  для <br>начинающих и профессиональных программистов и IT-cпециалистов</p>
            <hr> 
            <div class="com-blog">
                {% for b in blogs %}
                    <div class="main-info"> 
                        {% if b.image %}
                            <img src="{{ b.image.url }}" alt="comment-img" class="comment-img">
                        {% endif %}
                        <h2 id="blog-name" href="{% url 'decode_blogs:blog-search' %}">{{ b.name }}</h2>  
                        <hr>
                    </div>
                    <p id="description">{{ b.description }}</p>
                    <hr>
                    <div class="blog-review">
                        <time id="blog-date"><img src="{% static 'decode_blogs/images/Calendar.png' %}" alt="">{{ b.date }}</time>
                        <a href="{% url 'decode_blogs:category' b.category_id %}"><img src="{% static 'decode_blogs/images/Categories.png' %}" alt="" id="blog-categories">{{ b.category }}</a>
                        <a href="{% url 'decode_blogs:comments-category' b.id %}"><img src="{% static 'decode_blogs/images/Comment.png' %}" alt="" id="blog-comments"></a>
                        <img src="{% static 'decode_blogs/images/User.png' %}" alt="">{{ b.author }}
                    </div>
                    <hr>
                {% endfor %}
            </div>
  
            <div class="categories">
                <h2 id="categories-name">Категории</h2>
                {% if category_id == 0 %}
                    <a href="{% url 'decode_blogs:home' %}" class="selected-ctgr"></a>
                {% else %}
                    <a href="{% url 'decode_blogs:home' %}">Все Блоги</a>
                {% endif %}

                {% for ctgr in categories %}
                    {% if category_id == ctgr.id %}
                        <a href="{% url 'decode_blogs:category' ctgr.id %}" class="selected-ctgr">{{ctgr.name}}</a>
                    {% else %}
                        <a href="{% url 'decode_blogs:category' ctgr.id %}">{{ctgr.name}}</a>
                    {% endif %}
                {% endfor %}   
            </div>
        </div>
    </section>
</body>
</html>

blog/decode_blogs/templates/decode_blogs/comment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comment review</title>
    <link rel="stylesheet" href="{% static 'decode_blogs/css/comments.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_blogs/css/Home.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        
        <div class="header-div-2">
            {% if request.user.is_authenticated %}
                <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
                <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>
                {% if user.image %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
                {% else %}
                    <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
                {% endif %}

            {% else %}
                <a href="{% url 'decode_authe:signin' %}">SignIn</a>
            {% endif %}
        </div>
    </header>
    <hr>

    <section class="main">
        <div class="blogs">
            <div class="com-blog">
                <div class="main-info"> 
                    {% if blog.image %}
                    <img src="{{ blog.image.url }}" alt="comment-img" class="comment-img">
                    {% endif %}
                </div>
                <h2 id="blog-name">{{ blog.name }}</h2>
                <hr>
                    <p id="description">{{ blog.description }}</p>
                    <hr>
                    <time id="blog-date"><img src="{% static 'decode_blogs/images/Calendar.png' %}" alt="">{{ blog.date }}</time>
                    <a href="{% url 'decode_blogs:category' blog.id %}" id="blog-category"><img src="{% static 'decode_blogs/images/Categories.png' %}" alt="">{{ blog.category }}</a>
                    <img src="{% static 'decode_blogs/images/User.png' %}" alt="" id="blog-author">{{ blog.author }}
                    <hr>
            </div>
        </div>
        <div class="categories">
            <h2 id="categories-name">Категории</h2>
            {% if category_id == 0 %}
                <a href="{% url 'decode_blogs:home' %}" class="selected-ctgr">Все Блоги</a>
            {% else %}
                <a href="{% url 'decode_blogs:home' %}">Все Блоги</a>
            {% endif %}

            {% for ctgr in categories %}
                {% if category_id == ctgr.id %}
                    <a href="{% url 'decode_blogs:category' ctgr.id %}" class="selected-ctgr">{{ctgr.name}}</a>
                {% else %}
                    <a href="{% url 'decode_blogs:category' ctgr.id %}">{{ctgr.name}}</a>
                {% endif %}
            {% endfor %}    
    </section>

    <section class="main-3">
        <div class="comm-details">
            {% for c in comments %}
            <div class="comment">
                <div class="comm-detail">
                    <p id="user">{{ c.user }};</p> 
                    <p>{{ c.date }}</p>
                </div>
                <p id="text">{{ c.text }}</p>
                <hr id="com-line">
                {% if request.user.is_staff %}
                <a href="{% url 'decode_blogs:delete-comment' c.id %}" id="button-com">Удалить комментарий</a>
                {% endif %}
            </div>
        </div>
            {% endfor %}

            {% if request.user.is_authenticated %}
                <a href="{% url 'decode_blogs:cmadd' %}" id="button-com">Добавить комментарий</a>
            {% else %}
                <a href="{% url 'decode_authe:signin' %}" id="button-come">SignIn</a>
            {% endif %}
    </section>

</body>
</html>