blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Blogs API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('decode_blogs.urls')),
    path('authe/', include('decode_authe.urls')),
    url('swagger/', schema_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/decode_authe/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from . import views


app_name = 'decode_authe'

urlpatterns = [
    path('signup/',views.SignUpUser.as_view(), name='signup'),
    path('signin/',views.SignInUser.as_view() ,name='signin'),
    path('signout/',views.signout_user , name='signout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),


    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/user/', views.UserViewSet.as_view({'get': 'retrieve', 'post': 'create'})),

]

blog/decode_blogs/urls.py
from django.urls import path, include
from . import views

app_name = 'decode_blogs'

urlpatterns = [
    path('', views.Home, name="home"),
    path('blogs/<int:category_id>/', views.site_category, name='category'),
    path('add/', views.AddBlog.as_view(), name='add'),
    path('search/', views.BlogSearchView.as_view(), name='blog-search'), # ! #
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete'), 
    path('edit_blog/<int:blog_id>/', views.EditBlog.as_view(), name='edit'),


    path('cmadd/', views.AddComment.as_view(), name='cmadd'),
    path('testcommentview/<int:blog_id>/', views.BlogDetail.as_view(), name='comments-category'),
    path('delete_comment/<int:blog_id>/', views.delete_comment, name='delete-comment'), 

    
    path('', include('rest_framework.urls')),
    path('', views.BlogListAPIView.as_view()),
    path('<int:pk>/',views.BlogDetailAPIView.as_view()),
]

blog/decode_authe/models.py
from django.contrib.auth.models import User
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser

def uniq_name_upload(instance, filename):
    new_file_name = f"{uuid.uuid4()}.{filename.split('.')[-1]}"
    return f'avatars/{new_file_name}'


# Create your models here.
class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='avatars', blank=True)
    description = models.TextField(max_length=200)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='users',
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='users',
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
        error_messages={
            'add': 'The permission you are trying to add already exists for the user.',
            'remove': 'The permission you are trying to remove does not exist for the user.',
        },
    )

blog/decode_authe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.db import models
from PIL import Image
from .models import *

class SignUpUserForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('image','username', 'email','first_name', 'last_name', 'password1', 'password2',)

        widgets = {
            'username': forms.TextInput(attrs={'class':'from-input'}),
        }       

class EditProfileForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('image','username', 'email','first_name', 'last_name',)

blog/decode_authe/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from rest_framework.generics import RetrieveAPIView
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rest_framework import mixins

from .models import *
from .forms import *
from .serializers import *
from decode_blogs.models import Blog

# Create your views here.
menu = [
    {'title':'Home', 'url':'decode_blogs:home'},
    {'title':'Description', 'url':'decode_blogs:category'},
    {'title':'Регистрация', 'url':'decode_authe:signup'},
    {'title':'Вход', 'url':'decode_authe:signin'}
]

class SignUpUser(CreateView):
    form_class = SignUpUserForm
    template_name = 'decode_authe/signup.html'
    success_url = reverse_lazy('decode_blogs:home')     # Переход после создания пользователя #

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)

        context['title'] = 'Регистрация'
        context['menu'] = menu

        return context
    
class SignInUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'decode_authe/signin.html'


    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)

        context['title'] = 'Авторизация'
        context['menu'] = menu

        return context
    
    def get_success_url(self):
        return reverse_lazy('decode_blogs:home')



class UserDetailAPIView(RetrieveAPIView):
    def get_queryset(self):
        return User.objects.get(id=self.request.user.id)
    
class UserViewSet(GenericViewSet, mixins.CreateModelMixin,):
    def get_queryset(self):
        if self.action == 'retrieve':
            return User.objects.get(id=self.request.user.id)
        return User.objects.all()

    def get_serializer_class(self):
        if self.action == 'create':
            return UserCreateSerializer
        elif self.action == 'retrieve':
            return UserRetrieveSerializer
        
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_queryset()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

def signout_user(request):             # Выход из аккаунта  #
    logout(request)   
    return redirect('decode_authe:signin')     

def profile(request):
    if not request.user.is_authenticated:
        return redirect('decode_authe:signin')

    user_blogs = Blog.objects.filter(author=request.user)

    data = {
        'title': 'Профиль',
        'menu': menu,
        'user_blogs': user_blogs,   # Передаем отфильтрованные блоги
    }
    return render(request, 'decode_authe/profile.html', context=data)


@login_required             # Только зарегистрированные user-ы #
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user) # использование данных user-a для редактирования #
        if form.is_valid():
            form.save()
            return redirect('decode_authe:profile')  
    else:
        form = EditProfileForm(instance=request.user)
    
    return render(request, 'decode_authe/edit-profile.html', {'form': form})

blog/decode_authe/templates/decode_authe/edit-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit profile</title>
    <link rel="stylesheet" href="{% static 'decode_authe/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_authe/css/authe.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        <div class="header-div-2">
            <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
            <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>
            {% if user.image %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}
        </div>
    </header>
    <hr id="hr-line">

    <section class="authe-main">
        <h1>Редактирование профиля</h1>
        <form method="post" class="authe-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </section>
</body>
</html>

blog/decode_authe/templates/decode_authe/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль</title>
    <link rel="stylesheet" href="{% static 'decode_authe/css/authe.css' %}">
    <link rel="stylesheet" href="{% static 'decode_authe/css/Header.css' %}">

</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

        
        
        <div class="header-div-2">
            <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
            <a href="{% url 'decode_authe:signout' %}" class="button-reg">Signout</a>
            {% if user.image %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'decode_authe:profile'%}"><img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}
        </div>
    </header>
    <hr id="hr-line">
    
    <section class="main">
        <div class="com-blog">
            {% for b in user_blogs %}
            <div class="main-info"> 
                {% if b.image %}
                <img src="{{ b.image.url }}" alt="comment-img" class="comment-img">
                {% endif %}
            </div>
            <h2 id="blog-name">{{ b.name }}</h2>
            <p id="description">{{ b.description }}</p>
            <div class="blog-change">
                <a href="{% url 'decode_blogs:edit' b.id  %}" class="blog-button">Изменить блог</a>
                <a href="{% url 'decode_blogs:delete' b.id %}" class="blog-button">Удалить блог</a>
            </div>
            <hr>
            <div class="blog-review">
                <time id="blog-date"><img src="{% static 'decode_blogs/images/Calendar.png' %}" alt="">{{ b.date }}</time>
                <a href="{% url 'decode_blogs:category' b.id %}"><img src="{% static 'decode_blogs/images/Categories.png' %}" alt="" id="blog-categories">{{ b.category }}</a>
                <a href="{% url 'decode_blogs:comments-category' b.id %}"><img src="{% static 'decode_blogs/images/Comment.png' %}" alt="" id="blog-comments"></a>
                <img src="{% static 'decode_blogs/images/User.png' %}" alt="">{{ b.author }}
            </div>
            <hr>
            {% endfor %}
        </div>
    </section>

    <section class="profile-main">
        <span>
            {% if user.image %}
            <img src="{{ user.image.url }}" alt="" class="profile-img">
            {% else %}
                <img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}
        </span>
        <div class="profile-info">
            <p>
                <span>{{ user.username }}</span>
            </p>

            <p>
                <span>{{ user.first_name }}</span>
            </p>

            <p>
                <span>{{ user.last_name }}</span>
            </p>

            <p>
                <span>{{ user.email }}</span>
            </p>
        </div>

        {% if request.user.is_authenticated %}
            <div class="admin-links">
                <a href="{% url 'decode_authe:edit_profile' %}" class="blog-button">Редактировать профиль</a>      
                <a href="{% url 'decode_blogs:add' %}" class="blog-button"> Добавить новый блог</a>
            </div>
        {% endif %}
    </section>
</body>
</html>

blog/decode_authe/templates/decode_authe/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="{% static 'decode_authe/css/Authe.css' %}">
    <link rel="stylesheet" href="{% static 'decode_authe/css/header.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>


        <div class="header-div-2">
            <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
            <a href="{% url 'decode_authe:signup' %}" class="button-reg">SignUp</a>    
        </div>
    </header>
    <hr id="hr-line">


    <section class="authe-main">
        <h1>Авторизация</h1>

        <form action="" method="POST" class="authe-form">
            {% csrf_token %}
            
            {{ form.as_p }}
            
            <button type="submit">Зарегистрироваться</button>
        </form>
    </section>
</body>
</html>

blog/decode_authe/templates/decode_authe/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'decode_authe/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'decode_authe/css/authe.css' %}">

</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'decode_blogs:blog-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    <img src="{% static 'decode_blogs/images/search_icon.svg' %}" alt="" id="search_icon">
                    Search
                </button>
            </form> 
        </div>

    
        <div class="header-div-2">
            <a href="{% url 'decode_authe:signin' %}" class="button-reg">SignIn</a>
            <a href="{% url 'decode_blogs:home' %}" class="button-reg">Home</a>
        </div>
    </header>
    <hr id="hr-line">


    <section class="authe-main">
        <h1>Регистрация</h1>

        <form action="" method="POST" class="authe-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    </section>
</body>
</html>